source 'https://rubygems.org'

ruby '2.6.3'

gem 'rspec', '~>3.8.0'
gem 'selenium-webdriver', '~>4.0.0.alpha.2'
gem 'parallel_tests', '~>2.29.1'
gem 'rake', '~>12.3.2'
gem 'rspec_junit_formatter', '~>0.4.1'
